var e;e||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},e),ba=(a,b)=>{throw b;},ca="object"==typeof window,k="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",x,y,ea;
if(da){var fs=require("fs"),fa=require("path");p=k?fa.dirname(p)+"/":__dirname+"/";x=(a,b)=>{a=ha(a)?new URL(a):fa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ea=a=>{a=x(a,!0);a.buffer||(a=new Uint8Array(a));return a};y=(a,b,c,d=!0)=>{a=ha(a)?new URL(a):fa.normalize(a);fs.readFile(a,d?void 0:"utf8",(f,g)=>{f?c(f):b(d?g.buffer:g)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ia||a.context instanceof
ia))throw a;});ba=(a,b)=>{process.exitCode=a;throw b;};e.inspect=()=>"[Emscripten Module object]"}else if(ca||k)k?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):"",x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
y=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=e.print||console.log.bind(console),C=e.printErr||console.error.bind(console);Object.assign(e,aa);aa=null;e.quit&&(ba=e.quit);var ka;e.wasmBinary&&(ka=e.wasmBinary);"object"!=typeof WebAssembly&&la("no native wasm support detected");var ma,na=!1,D,E,oa,F,H;
function pa(){var a=ma.buffer;e.HEAP8=D=new Int8Array(a);e.HEAP16=oa=new Int16Array(a);e.HEAPU8=E=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU32=H=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var qa=[],ra=[],sa=[];function ta(){var a=e.preRun.shift();qa.unshift(a)}var I=0,ua=null,va=null;function wa(){I++;e.monitorRunDependencies?.(I)}
function xa(){I--;e.monitorRunDependencies?.(I);if(0==I&&(null!==ua&&(clearInterval(ua),ua=null),va)){var a=va;va=null;a()}}function la(a){e.onAbort?.(a);a="Aborted("+a+")";C(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),ha=a=>a.startsWith("file://"),J;J="model.wasm";if(!ya(J)){var za=J;J=e.locateFile?e.locateFile(za,p):p+za}
function Aa(a){if(a==J&&ka)return new Uint8Array(ka);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){if(!ka&&(ca||k)){if("function"==typeof fetch&&!ha(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(y)return new Promise((b,c)=>{y(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{C(`failed to asynchronously prepare wasm: ${d}`);la(d)})}function Da(a,b){var c=J;ka||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||ha(c)||da||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){C(`wasm streaming compile failed: ${f}`);C("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}var K,Ea;
function ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(e)},Ga=e.noExitRuntime||!0,Ha=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ia=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.substr(0,b.length-1);return a+b},N=a=>{if("/"===a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ja=(a,b)=>L(a+"/"+b),Ka=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(da)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}la("initRandomDevice")},La=a=>(La=Ka())(a);
function O(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:P.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ha(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ma=(a,b)=>{function c(h){for(var n=0;n<h.length&&""===h[n];n++);for(var q=h.length-1;0<=q&&""===h[q];q--);return n>q?[]:h.slice(n,q-n+1)}a=O(a).substr(1);b=O(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},Na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Q=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&
a.buffer&&Na)return Na.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Oa=[],Pa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Qa=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f};
function Ra(a){var b=Array(Pa(a)+1);a=Qa(a,b,0,b.length);b.length=a;return b}var Sa=[];function Ta(a,b){Sa[a]={input:[],output:[],O:b};Ua(a,Va)}
var Va={open(a){var b=Sa[a.node.rdev];if(!b)throw new P.o(43);a.tty=b;a.seekable=!1},close(a){a.tty.O.fsync(a.tty)},fsync(a){a.tty.O.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.O.pa)throw new P.o(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.O.pa(a.tty)}catch(n){throw new P.o(29);}if(void 0===h&&0===f)throw new P.o(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.O.ha)throw new P.o(60);try{for(var f=0;f<d;f++)a.tty.O.ha(a.tty,
b[c+f])}catch(g){throw new P.o(29);}d&&(a.node.timestamp=Date.now());return f}},Wa={pa(){a:{if(!Oa.length){var a=null;if(da){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Oa=
Ra(a)}a=Oa.shift()}return a},ha(a,b){null===b||10===b?(ja(Q(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ja(Q(a.output,0)),a.output=[])},Ha(){return{Sa:25856,Ua:5,Ra:191,Ta:35387,Qa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ia(){return 0},Ja(){return[24,80]}},Xa={ha(a,b){null===b||10===b?(C(Q(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(C(Q(a.output,0)),a.output=[])}},Za=a=>
{a=65536*Math.ceil(a/65536);var b=Ya(65536,a);b?(E.fill(0,b,b+a),a=b):a=0;return a};function $a(a,b){var c=a.A?a.A.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.A,a.A=new Uint8Array(b),0<a.B&&a.A.set(c.subarray(0,a.B),0))}
var R={K:null,C(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||P.isFIFO(c))throw new P.o(63);R.K||(R.K={dir:{node:{H:R.u.H,D:R.u.D,lookup:R.u.lookup,M:R.u.M,rename:R.u.rename,unlink:R.u.unlink,rmdir:R.u.rmdir,readdir:R.u.readdir,symlink:R.u.symlink},stream:{I:R.v.I}},file:{node:{H:R.u.H,D:R.u.D},stream:{I:R.v.I,read:R.v.read,write:R.v.write,U:R.v.U,S:R.v.S,X:R.v.X}},link:{node:{H:R.u.H,D:R.u.D,readlink:R.u.readlink},stream:{}},ma:{node:{H:R.u.H,D:R.u.D},stream:P.Ca}});
c=P.createNode(a,b,c,d);S(c.mode)?(c.u=R.K.dir.node,c.v=R.K.dir.stream,c.A={}):P.isFile(c.mode)?(c.u=R.K.file.node,c.v=R.K.file.stream,c.B=0,c.A=null):40960===(c.mode&61440)?(c.u=R.K.link.node,c.v=R.K.link.stream):8192===(c.mode&61440)&&(c.u=R.K.ma.node,c.v=R.K.ma.stream);c.timestamp=Date.now();a&&(a.A[b]=c,a.timestamp=c.timestamp);return c},$a(a){return a.A?a.A.subarray?a.A.subarray(0,a.B):new Uint8Array(a.A):new Uint8Array(0)},u:{H(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;S(a.mode)?b.size=4096:P.isFile(a.mode)?b.size=a.B:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Aa=4096;b.blocks=Math.ceil(b.size/b.Aa);return b},D(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.B!=b))if(0==b)a.A=null,a.B=0;else{var c=a.A;a.A=new Uint8Array(b);c&&a.A.set(c.subarray(0,
Math.min(b,a.B)));a.B=b}},lookup(){throw P.aa[44];},M(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){if(S(a.mode)){try{var d=T(b,c)}catch(g){}if(d)for(var f in d.A)throw new P.o(55);}delete a.parent.A[a.name];a.parent.timestamp=Date.now();a.name=c;b.A[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.A[b];a.timestamp=Date.now()},rmdir(a,b){var c=T(a,b),d;for(d in c.A)throw new P.o(55);delete a.A[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.A))b.push(c);
return b},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new P.o(28);return a.link}},v:{read(a,b,c,d,f){var g=a.node.A;if(f>=a.node.B)return 0;a=Math.min(a.node.B-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write(a,b,c,d,f,g){b.buffer===D.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.A||a.A.subarray)){if(g)return a.A=b.subarray(c,c+d),a.B=d;if(0===a.B&&
0===f)return a.A=b.slice(c,c+d),a.B=d;if(f+d<=a.B)return a.A.set(b.subarray(c,c+d),f),d}$a(a,f+d);if(a.A.subarray&&b.subarray)a.A.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.A[f+g]=b[c+g];a.B=Math.max(a.B,f+d);return d},I(a,b,c){1===c?b+=a.position:2===c&&P.isFile(a.node.mode)&&(b+=a.node.B);if(0>b)throw new P.o(28);return b},U(a,b,c){$a(a.node,b+c);a.node.B=Math.max(a.node.B,b+c)},S(a,b,c,d,f){if(!P.isFile(a.node.mode))throw new P.o(43);a=a.node.A;if(f&2||a.buffer!==D.buffer){if(0<c||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=Za(b);if(!b)throw new P.o(48);D.set(a,b)}else c=!1,b=a.byteOffset;return{ua:b,ka:c}},X(a,b,c,d){R.v.write(a,b,0,d,c,!1);return 0}}},ab=(a,b,c)=>{var d=`al ${a}`;y(a,f=>{f||la(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(f));d&&xa()},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&wa()},bb=e.preloadPlugins||[],cb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.V();var f=!1;bb.forEach(g=>{!f&&
g.canHandle(b)&&(g.handle(a,b,c,d),f=!0)});return f},db=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};function Ua(a,b){P.oa[a]={v:b}}function S(a){return 16384===(a&61440)}function T(a,b){var c;if(c=(c=U(a,"x"))?c:a.u.lookup?0:2)throw new P.o(c,a);for(c=P.J[eb(a.id,b)];c;c=c.T){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return P.lookup(a,b)}
function V(a,b={}){a=O(a);if(!a)return{path:"",node:null};b=Object.assign({$:!0,ja:0},b);if(8<b.ja)throw new P.o(32);a=a.split("/").filter(h=>!!h);for(var c=P.root,d="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=T(c,a[f]);d=L(d+"/"+a[f]);c.F&&(!g||g&&b.$)&&(c=c.F.root);if(!g||b.G)for(g=0;40960===(c.mode&61440);)if(c=P.readlink(d),d=O(Ia(d),c),c=V(d,{ja:b.ja+1}).node,40<g++)throw new P.o(32);}return{path:d,node:c}}
function W(a){for(var b;;){if(P.sa(a))return a=a.C.ta,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.J.length}function fb(a){var b=eb(a.parent.id,a.name);a.T=P.J[b];P.J[b]=a}function gb(a){var b=eb(a.parent.id,a.name);if(P.J[b]===a)P.J[b]=a.T;else for(b=P.J[b];b;){if(b.T===a){b.T=a.T;break}b=b.T}}function hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function U(a,b){if(P.ra)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ib(a,b){try{return T(a,b),20}catch(c){}return U(a,"wx")}function jb(a,b,c){try{var d=T(a,b)}catch(f){return f.L}if(a=U(a,"wx"))return a;if(c){if(!S(d.mode))return 54;if(P.sa(d)||W(d)===P.cwd())return 10}else if(S(d.mode))return 31;return 0}function kb(){for(var a=0;a<=P.xa;a++)if(!P.streams[a])return a;throw new P.o(33);}
function X(a){a=P.Ga(a);if(!a)throw new P.o(8);return a}function lb(a){var b=-1;P.Y||(P.Y=function(){this.N={}},P.Y.prototype={},Object.defineProperties(P.Y.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.N.flags},set(c){this.N.flags=c}},position:{get(){return this.N.position},set(c){this.N.position=c}}}));a=Object.assign(new P.Y,a);-1==b&&(b=kb());a.fd=b;return P.streams[b]=a}
function mb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.W)}return b}function nb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return P.M(a,b|8192,c)}function ob(){P.o||(P.o=function(a,b){this.name="ErrnoError";this.node=b;this.Na=function(c){this.L=c};this.Na(a);this.message="FS error"},P.o.prototype=Error(),P.o.prototype.constructor=P.o,[44].forEach(a=>{P.aa[a]=new P.o(a);P.aa[a].stack="<generic error, no stack>"}))}
function pb(a,b,c,d){a="string"==typeof a?a:W(a);b=L(a+"/"+b);return P.create(b,db(c,d))}
function qb(a){if(!(a.Ka||a.La||a.link||a.A)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(x)try{a.A=Ra(x(a.url)),a.B=a.A.length}catch(b){throw new P.o(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
var P={root:null,W:[],oa:{},streams:[],Ma:1,J:null,na:"/",da:!1,ra:!0,o:null,aa:{},Ea:null,Z:0,createNode(a,b,c,d){a=new P.wa(a,b,c,d);fb(a);return a},sa(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},xa:4096,Ga:a=>P.streams[a],Ca:{open(a){a.v=P.Fa(a.node.rdev).v;a.v.open?.(a)},I(){throw new P.o(70);}},ga:a=>a>>8,ab:a=>a&255,R:(a,b)=>a<<8|b,Fa:a=>P.oa[a],va(a,b){function c(h){P.Z--;return b(h)}function d(h){if(h){if(!d.Da)return d.Da=
!0,c(h)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);P.Z++;1<P.Z&&C(`warning: ${P.Z} FS.syncfs operations in flight at once, probably just doing extra work`);var f=mb(P.root.C),g=0;f.forEach(h=>{if(!h.type.va)return d(null);h.type.va(h,a,d)})},C(a,b,c){var d="/"===c,f=!c;if(d&&P.root)throw new P.o(10);if(!d&&!f){var g=V(c,{$:!1});c=g.path;g=g.node;if(g.F)throw new P.o(10);if(!S(g.mode))throw new P.o(54);}b={type:a,eb:b,ta:c,W:[]};a=a.C(b);a.C=b;b.root=a;d?P.root=a:g&&(g.F=b,g.C&&g.C.W.push(b));
return a},gb(a){a=V(a,{$:!1});if(!a.node.F)throw new P.o(28);a=a.node;var b=a.F,c=mb(b);Object.keys(P.J).forEach(d=>{for(d=P.J[d];d;){var f=d.T;c.includes(d.C)&&gb(d);d=f}});a.F=null;a.C.W.splice(a.C.W.indexOf(b),1)},lookup(a,b){return a.u.lookup(a,b)},M(a,b,c){var d=V(a,{parent:!0}).node;a=N(a);if(!a||"."===a||".."===a)throw new P.o(28);var f=ib(d,a);if(f)throw new P.o(f);if(!d.u.M)throw new P.o(63);return d.u.M(d,a,b,c)},create(a,b){return P.M(a,(void 0!==b?b:438)&4095|32768,0)},mkdir(a,b){return P.M(a,
(void 0!==b?b:511)&1023|16384,0)},bb(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{P.mkdir(c,b)}catch(f){if(20!=f.L)throw f;}}},symlink(a,b){if(!O(a))throw new P.o(44);var c=V(b,{parent:!0}).node;if(!c)throw new P.o(44);b=N(b);var d=ib(c,b);if(d)throw new P.o(d);if(!c.u.symlink)throw new P.o(63);return c.u.symlink(c,b,a)},rename(a,b){var c=Ia(a),d=Ia(b),f=N(a),g=N(b);var h=V(a,{parent:!0});var n=h.node;h=V(b,{parent:!0});h=h.node;if(!n||!h)throw new P.o(44);if(n.C!==
h.C)throw new P.o(75);var q=T(n,f);a=Ma(a,d);if("."!==a.charAt(0))throw new P.o(28);a=Ma(b,c);if("."!==a.charAt(0))throw new P.o(55);try{var m=T(h,g)}catch(r){}if(q!==m){b=S(q.mode);if(f=jb(n,f,b))throw new P.o(f);if(f=m?jb(h,g,b):ib(h,g))throw new P.o(f);if(!n.u.rename)throw new P.o(63);if(q.F||m&&m.F)throw new P.o(10);if(h!==n&&(f=U(n,"w")))throw new P.o(f);gb(q);try{n.u.rename(q,h,g)}catch(r){throw r;}finally{fb(q)}}},rmdir(a){var b=V(a,{parent:!0}).node;a=N(a);var c=T(b,a),d=jb(b,a,!0);if(d)throw new P.o(d);
if(!b.u.rmdir)throw new P.o(63);if(c.F)throw new P.o(10);b.u.rmdir(b,a);gb(c)},readdir(a){a=V(a,{G:!0}).node;if(!a.u.readdir)throw new P.o(54);return a.u.readdir(a)},unlink(a){var b=V(a,{parent:!0}).node;if(!b)throw new P.o(44);a=N(a);var c=T(b,a),d=jb(b,a,!1);if(d)throw new P.o(d);if(!b.u.unlink)throw new P.o(63);if(c.F)throw new P.o(10);b.u.unlink(b,a);gb(c)},readlink(a){a=V(a).node;if(!a)throw new P.o(44);if(!a.u.readlink)throw new P.o(28);return O(W(a.parent),a.u.readlink(a))},stat(a,b){a=V(a,
{G:!b}).node;if(!a)throw new P.o(44);if(!a.u.H)throw new P.o(63);return a.u.H(a)},lstat(a){return P.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?V(a,{G:!c}).node:a;if(!a.u.D)throw new P.o(63);a.u.D(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod(a,b){P.chmod(a,b,!0)},fchmod(a,b){a=X(a);P.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?V(a,{G:!d}).node:a;if(!a.u.D)throw new P.o(63);a.u.D(a,{timestamp:Date.now()})},lchown(a,b,c){P.chown(a,b,c,!0)},fchown(a,b,c){a=X(a);P.chown(a.node,
b,c)},truncate(a,b){if(0>b)throw new P.o(28);a="string"==typeof a?V(a,{G:!0}).node:a;if(!a.u.D)throw new P.o(63);if(S(a.mode))throw new P.o(31);if(!P.isFile(a.mode))throw new P.o(28);var c=U(a,"w");if(c)throw new P.o(c);a.u.D(a,{size:b,timestamp:Date.now()})},Za(a,b){a=X(a);if(0===(a.flags&2097155))throw new P.o(28);P.truncate(a.node,b)},hb(a,b,c){a=V(a,{G:!0}).node;a.u.D(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new P.o(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,
a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=L(a);try{f=V(a,{G:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new P.o(20);}else f=P.M(a,c,0),d=!0;if(!f)throw new P.o(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!S(f.mode))throw new P.o(54);if(!d&&(c=f?40960===(f.mode&61440)?32:S(f.mode)&&("r"!==hb(b)||b&512)?31:U(f,hb(b)):44))throw new P.o(c);
b&512&&!d&&P.truncate(f,0);b&=-131713;f=lb({node:f,path:W(f),flags:b,seekable:!0,position:0,v:f.v,Pa:[],error:!1});f.v.open&&f.v.open(f);!e.logReadFiles||b&1||(P.ia||(P.ia={}),a in P.ia||(P.ia[a]=1));return f},close(a){if(null===a.fd)throw new P.o(8);a.ba&&(a.ba=null);try{a.v.close&&a.v.close(a)}catch(b){throw b;}finally{P.streams[a.fd]=null}a.fd=null},I(a,b,c){if(null===a.fd)throw new P.o(8);if(!a.seekable||!a.v.I)throw new P.o(70);if(0!=c&&1!=c&&2!=c)throw new P.o(28);a.position=a.v.I(a,b,c);a.Pa=
[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new P.o(28);if(null===a.fd)throw new P.o(8);if(1===(a.flags&2097155))throw new P.o(8);if(S(a.node.mode))throw new P.o(31);if(!a.v.read)throw new P.o(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new P.o(70);b=a.v.read(a,b,c,d,f);g||(a.position+=b);return b},write(a,b,c,d,f,g){if(0>d||0>f)throw new P.o(28);if(null===a.fd)throw new P.o(8);if(0===(a.flags&2097155))throw new P.o(8);if(S(a.node.mode))throw new P.o(31);
if(!a.v.write)throw new P.o(28);a.seekable&&a.flags&1024&&P.I(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new P.o(70);b=a.v.write(a,b,c,d,f,g);h||(a.position+=b);return b},U(a,b,c){if(null===a.fd)throw new P.o(8);if(0>b||0>=c)throw new P.o(28);if(0===(a.flags&2097155))throw new P.o(8);if(!P.isFile(a.node.mode)&&!S(a.node.mode))throw new P.o(43);if(!a.v.U)throw new P.o(138);a.v.U(a,b,c)},S(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new P.o(2);
if(1===(a.flags&2097155))throw new P.o(2);if(!a.v.S)throw new P.o(43);return a.v.S(a,b,c,d,f)},X(a,b,c,d,f){return a.v.X?a.v.X(a,b,c,d,f):0},cb:()=>0,ea(a,b,c){if(!a.v.ea)throw new P.o(59);return a.v.ea(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=P.open(a,b.flags);a=P.stat(a).size;var f=new Uint8Array(a);P.read(d,f,0,a,0);"utf8"===b.encoding?c=Q(f,0):"binary"===
b.encoding&&(c=f);P.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=P.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Pa(b)+1);b=Qa(b,d,0,d.length);P.write(a,d,0,b,void 0,c.Ba)}else if(ArrayBuffer.isView(b))P.write(a,b,0,b.byteLength,void 0,c.Ba);else throw Error("Unsupported data type");P.close(a)},cwd:()=>P.na,chdir(a){a=V(a,{G:!0});if(null===a.node)throw new P.o(44);if(!S(a.node.mode))throw new P.o(54);var b=U(a.node,"x");if(b)throw new P.o(b);P.na=a.path},V(a,
b,c){P.V.da=!0;ob();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;e.stdin?P.P("/dev","stdin",e.stdin):P.symlink("/dev/tty","/dev/stdin");e.stdout?P.P("/dev","stdout",null,e.stdout):P.symlink("/dev/tty","/dev/stdout");e.stderr?P.P("/dev","stderr",null,e.stderr):P.symlink("/dev/tty1","/dev/stderr");P.open("/dev/stdin",0);P.open("/dev/stdout",1);P.open("/dev/stderr",1)},fb(){P.V.da=!1;for(var a=0;a<P.streams.length;a++){var b=P.streams[a];b&&P.close(b)}},Ya(a,b){try{var c=V(a,{G:!b});
a=c.path}catch(g){}var d=!1,f=null;try{c=V(a,{parent:!0}),N(a),c=V(a,{G:!b}),d=!0,f=c.node}catch(g){}return d?f:null},Wa(a,b){a="string"==typeof a?a:W(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{P.mkdir(d)}catch(f){}a=d}}return d},P(a,b,c,d){a=Ja("string"==typeof a?a:W(a),b);b=db(!!c,!!d);P.P.ga||(P.P.ga=64);var f=P.R(P.P.ga++,0);Ua(f,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,n,q){for(var m=0,r=0;r<q;r++){try{var l=c()}catch(t){throw new P.o(29);
}if(void 0===l&&0===m)throw new P.o(6);if(null===l||void 0===l)break;m++;h[n+r]=l}m&&(g.node.timestamp=Date.now());return m},write(g,h,n,q){for(var m=0;m<q;m++)try{d(h[n+m])}catch(r){throw new P.o(29);}q&&(g.node.timestamp=Date.now());return m}});return nb(a,b,f)},Va(a,b,c,d,f){function g(){this.fa=!1;this.N=[]}function h(l,t,z,v,u){l=l.node.A;if(u>=l.length)return 0;v=Math.min(l.length-u,v);if(l.slice)for(var w=0;w<v;w++)t[z+w]=l[u+w];else for(w=0;w<v;w++)t[z+w]=l.get(u+w);return v}g.prototype.get=
function(l){if(!(l>this.length-1||0>l)){var t=l%this.chunkSize;return this.qa(l/this.chunkSize|0)[t]}};g.prototype.Oa=function(l){this.qa=l};g.prototype.la=function(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var t=Number(l.getResponseHeader("Content-length")),z,v=(z=l.getResponseHeader("Accept-Ranges"))&&"bytes"===z;l=(z=l.getResponseHeader("Content-Encoding"))&&"gzip"===z;var u=
1048576;v||(u=t);var w=this;w.Oa(B=>{var G=B*u,M=(B+1)*u-1;M=Math.min(M,t-1);if("undefined"==typeof w.N[B]){var yb=w.N;if(G>M)throw Error("invalid range ("+G+", "+M+") or no bytes requested!");if(M>t-1)throw Error("only "+t+" bytes available! programmer error!");var A=new XMLHttpRequest;A.open("GET",c,!1);t!==u&&A.setRequestHeader("Range","bytes="+G+"-"+M);A.responseType="arraybuffer";A.overrideMimeType&&A.overrideMimeType("text/plain; charset=x-user-defined");A.send(null);if(!(200<=A.status&&300>
A.status||304===A.status))throw Error("Couldn't load "+c+". Status: "+A.status);G=void 0!==A.response?new Uint8Array(A.response||[]):Ra(A.responseText||"");yb[B]=G}if("undefined"==typeof w.N[B])throw Error("doXHR failed!");return w.N[B]});if(l||!t)u=t=1,u=t=this.qa(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.za=t;this.ya=u;this.fa=!0};if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var n=new g;Object.defineProperties(n,{length:{get:function(){this.fa||this.la();return this.za}},chunkSize:{get:function(){this.fa||this.la();return this.ya}}});var q=void 0}else q=c,n=void 0;var m=pb(a,b,d,f);n?m.A=n:q&&(m.A=null,m.url=q);Object.defineProperties(m,{B:{get:function(){return this.A.length}}});var r={};Object.keys(m.v).forEach(l=>{var t=m.v[l];r[l]=function(){qb(m);return t.apply(null,arguments)}});r.read=(l,t,z,v,u)=>{qb(m);return h(l,t,z,v,u)};r.S=(l,t,z)=>{qb(m);var v=Za(t);if(!v)throw new P.o(48);
h(l,D,v,t,z);return{ua:v,ka:!0}};m.v=r;return m}},rb=void 0;function Y(){var a=F[+rb>>2];rb+=4;return a}var vb=(a,b,c,d)=>{var f={string:m=>{var r=0;if(null!==m&&void 0!==m&&0!==m){r=Pa(m)+1;var l=sb(r);Qa(m,E,l,r);r=l}return r},array:m=>{var r=sb(m.length);D.set(m,r);return r}};a=e["_"+a];var g=[],h=0;if(d)for(var n=0;n<d.length;n++){var q=f[c[n]];q?(0===h&&(h=tb()),g[n]=q(d[n])):g[n]=d[n]}c=a.apply(null,g);return c=function(m){0!==h&&ub(h);return"string"===b?m?Q(E,m):"":"boolean"===b?!!m:m}(c)};
function wb(a,b,c,d){a||=this;this.parent=a;this.C=a.C;this.F=null;this.id=P.Ma++;this.name=b;this.mode=c;this.u={};this.v={};this.rdev=d}Object.defineProperties(wb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},La:{get:function(){return S(this.mode)}},Ka:{get:function(){return 8192===(this.mode&61440)}}});P.wa=wb;
P.Xa=(a,b,c,d,f,g,h,n,q,m)=>{function r(t){function z(v){m?.();if(!n){var u=a,w=b;u&&(u="string"==typeof u?u:W(u),w=b?L(u+"/"+b):u);u=db(d,f);w=P.create(w,u);if(v){if("string"==typeof v){for(var B=Array(v.length),G=0,M=v.length;G<M;++G)B[G]=v.charCodeAt(G);v=B}P.chmod(w,u|146);B=P.open(w,577);P.write(B,v,0,v.length,0,q);P.close(B);P.chmod(w,u)}}g?.();xa()}cb(t,l,z,()=>{h?.();xa()})||z(t)}var l=b?O(L(a+"/"+b)):a;wa();"string"==typeof c?ab(c,t=>r(t),h):r(c)};ob();P.J=Array(4096);P.C(R,{},"/");P.mkdir("/tmp");
P.mkdir("/home");P.mkdir("/home/web_user");(function(){P.mkdir("/dev");Ua(P.R(1,3),{read:()=>0,write:(d,f,g,h)=>h});nb("/dev/null",P.R(1,3));Ta(P.R(5,0),Wa);Ta(P.R(6,0),Xa);nb("/dev/tty",P.R(5,0));nb("/dev/tty1",P.R(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=La(a).byteLength);return a[--b]};P.P("/dev","random",c);P.P("/dev","urandom",c);P.mkdir("/dev/shm");P.mkdir("/dev/shm/tmp")})();
(function(){P.mkdir("/proc");var a=P.mkdir("/proc/self");P.mkdir("/proc/self/fd");P.C({C(){var b=P.createNode(a,"fd",16895,73);b.u={lookup(c,d){var f=X(+d);c={parent:null,C:{ta:"fake"},u:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")})();P.Ea={MEMFS:R};
var xb={i:function(a,b,c){rb=c;try{var d=X(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.O.Ha){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=Y();F[f>>2]=25856;F[f+4>>2]=5;F[f+8>>2]=191;F[f+12>>2]=35387;for(var g=0;32>g;g++)D[f+g+17>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.O.Ia)for(f=Y(),a=[],g=0;32>g;g++)a.push(D[f+g+17>>0]);return 0;
case 21519:if(!d.tty)return-59;f=Y();return F[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Y(),P.ea(d,b,f);case 21523:if(!d.tty)return-59;d.tty.O.Ja&&(g=[24,80],f=Y(),oa[f>>1]=g[0],oa[f+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof P||"ErrnoError"!==h.name)throw h;return-h.L}},b:function(a,b,c,d){rb=d;try{b=b?Q(E,b):"";var f=b;if("/"===f.charAt(0))b=f;else{var g=-100===a?P.cwd():X(a).path;if(0==f.length)throw new P.o(44);
b=L(g+"/"+f)}var h=d?Y():0;return P.open(b,c,h).fd}catch(n){if("undefined"==typeof P||"ErrnoError"!==n.name)throw n;return-n.L}},c:function(a,b,c,d,f,g,h,n){f=g+2097152>>>0<4194305-!!f?(f>>>0)+4294967296*g:NaN;try{if(isNaN(f))return 61;var q=X(d),m=P.S(q,a,f,b,c),r=m.ua;F[h>>2]=m.ka;H[n>>2]=r;return 0}catch(l){if("undefined"==typeof P||"ErrnoError"!==l.name)throw l;return-l.L}},f:(a,b,c)=>E.copyWithin(a,b,b+c),e:a=>{var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=(f.min.call(f,2147483648,d+(65536-d%65536)%65536)-ma.buffer.byteLength+65535)/65536;try{ma.grow(f);pa();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},j:a=>{Ga||(e.onExit?.(a),na=!0);ba(a,new ia(a))},a:function(a){try{var b=X(a);P.close(b);return 0}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return c.L}},h:function(a,b,c,d){try{a:{var f=X(a);a=b;for(var g,h=b=0;h<c;h++){var n=H[a>>2],q=H[a+4>>2];a+=8;
var m=P.read(f,D,n,q,g);if(0>m){var r=-1;break a}b+=m;if(m<q)break;"undefined"!==typeof g&&(g+=m)}r=b}H[d>>2]=r;return 0}catch(l){if("undefined"==typeof P||"ErrnoError"!==l.name)throw l;return l.L}},d:function(a,b,c,d,f){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var g=X(a);P.I(g,b,d);Ea=[g.position>>>0,(K=g.position,1<=+Math.abs(K)?0<K?+Math.floor(K/4294967296)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];F[f>>2]=Ea[0];F[f+4>>2]=Ea[1];g.ba&&0===b&&0===d&&
(g.ba=null);return 0}catch(h){if("undefined"==typeof P||"ErrnoError"!==h.name)throw h;return h.L}},g:function(a,b,c,d){try{a:{var f=X(a);a=b;for(var g,h=b=0;h<c;h++){var n=H[a>>2],q=H[a+4>>2];a+=8;var m=P.write(f,D,n,q,g);if(0>m){var r=-1;break a}b+=m;"undefined"!==typeof g&&(g+=m)}r=b}H[d>>2]=r;return 0}catch(l){if("undefined"==typeof P||"ErrnoError"!==l.name)throw l;return l.L}}},Z=function(){function a(c){Z=c.exports;ma=Z.k;pa();ra.unshift(Z.l);xa();return Z}var b={a:xb};wa();if(e.instantiateWasm)try{return e.instantiateWasm(b,
a)}catch(c){return C(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da(b,function(c){a(c.instance)});return{}}();e._complete=a=>(e._complete=Z.m)(a);e._init=a=>(e._init=Z.n)(a);var Ya=(a,b)=>(Ya=Z.p)(a,b),tb=()=>(tb=Z.q)(),ub=a=>(ub=Z.r)(a),sb=a=>(sb=Z.s)(a);e.cwrap=(a,b,c,d)=>{var f=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&f&&!d?e["_"+a]:function(){return vb(a,b,c,arguments)}};e.FS=P;var zb;va=function Ab(){zb||Bb();zb||(va=Ab)};
function Bb(){function a(){if(!zb&&(zb=!0,e.calledRun=!0,!na)){e.noFSInit||P.V.da||P.V();P.ra=!1;Fa(ra);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();sa.unshift(b)}Fa(sa)}}if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ta();Fa(qa);0<I||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();Bb();
